### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by apu52**
Hello sir,
I have updated the README.md file by adding the API boxes in the readme file.
Please take a review of my PR & after reviewing if possible please merge it under APERTRE'24

### CODE REVIEW

**Comment by apu52** [comment]
@YuweAEC Please take a review of my PR & after reviewing if possible please merge it under APERTRE'24

**Comment by apu52** [comment]
@YuweAEC Please add the labels of APERTRE to the repo otherwise my points will not  be counted.

**Comment by apu52** [comment]
@YuweAEC Can you please add easy/medium/hard labels so that my point will be counted

**Comment by YuweAEC** [comment]
Okay 👍

**Pull request merged**
